### ISSUE TITLE
Errors...

### ISSUE THREAD

**Issue by JoostDkr** [dolorosus/RaspiBackup#16] opened 2024-09-30 19:57 UTC
Running the RaspiBackup ends with "[ok] SD Image backup process completed."
But..... is gives the next 3 errors:

rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]

partx: /dev/loop0: error adding partitions 1-2

IO error encountered -- skipping file deletion.

I have used different SD cards and tested on two Raspberries. Always these 3 errors appeared.....
Does someone recognize these errors? Is the backup reliable?

I have attached the log RaspiBackup.txt
[RaspiBackup.txt](https://github.com/user-attachments/files/17195937/RaspiBackup.txt)

**Comment by framps** [comment] 2024-09-30 20:09
I'm sorry but it seems to me you use some other backup tool called RaspiBackup. This backup tool is called raspiBackup (lower case r) and will produce a raspiBackup.log file and no RaspiBackup.txt. Also  your RaspiBackup.txt was not created by raspiBackup. The log file contents looks totally different.

> Is the backup reliable?

I wouldn't trust a backup with rsync errors.

**Comment by framps** [comment] 2024-09-30 20:23
Please ignore my previous comment I already deleted. By error I thought it's an issue for my backup tool raspiBackup :-(

**Comment by dolorosus** [comment] 2024-10-01 07:20
Hi,

the message ```partx: /dev/loop0: error adding partitions 1-2``` can be ignored when creating a backup for the first time.
For subsequent backups, I would first restart the Raspi and try again. As long as you have enough space in the imagefile, you can perform the backup as often as you like, only the changed files will be copied. 

I am not familiar with the ```rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]```  message. this message is caused by rsync, Is the your OS and your ```rsync``` version you are using up to date? 
For the current version of Raspian based on Debian GNU/Linux 12 (bookworm) it should be: 
```
# rsync --version
rsync  version 3.2.7  protocol version 31
```
Also you can try to get more information adding the ```-l``` option. 
 
Whether the backup is reliable can and **should** definitely be tested.
Simply copy the backup file to an empty SD card e.g. using the Raspberrypi imager (scroll all the way down under OS and select your own image). Insert this freshly created sd card into the Raspberrypi and test it extensively.

**Comment by JoostDkr** [comment] 2024-10-01 11:41
I found the rsync error in the log. The error say's: "rsync: readlink_stat("/home/pi/thinclient_drives") failed: Permission denied (13)".
Indeed the directory "thinclient_drives" is not acceable for me. Even "sudo ls" gives "Permission denied".
Also sudo chmod -R a+rxw ./thinclient_drives" gives "Permission denied".

Does somebody know how to solve this problem. For example making directory "thinclient_drives" readable?

**Comment by dolorosus** [comment] 2024-10-01 11:53
Seem to be related to xrdp setting extended attributes to this directory.

Use  ```lsattr``` to figure out what's happend and ```chattr``` to get access if you really need access.

**Comment by dolorosus** [comment] 2024-10-01 12:03
As far as I know xrdp creates ```thinclient_drives```
It should have the sticky bit (t) set. 
Here's the output from one of my systems: 
``` 
#stat thinclient_drives
 File: thinclient_drives
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 179,1   Inode: 339535      Links: 2
Access: (1755/drwxr-xr-t)  Uid: ( 1000/      la)   Gid: ( 1000/      la)
Access: 2024-09-12 19:59:50.588085241 +0200
Modify: 2024-09-12 19:59:50.588085241 +0200
Change: 2024-09-12 19:59:50.588085241 +0200
 Birth: 2024-09-12 19:59:50.588085241 +0200
```
You can try to set the owner/group to your primary user/group and the permissions to 1755 (```chmod 1755 thinclient_drives```) to get access.

**Comment by JoostDkr** [comment] 2024-10-01 12:07
It look's like there is a problem with thinclient_drives.......

pi@Raspberrypi-2:~ $ lsattr
--------------e---- ./MagPi
--------------e---- ./scripts
--------------e---- ./RonR-RPi-image-utils
--------------e---- ./Music
--------------e---- ./Pictures
--------------e---- ./Templates
--------------e---- ./Documents
--------------e---- ./Videos
--------------e---- ./raspiBackup.log
lsattr: Inappropriate ioctl for device While reading flags on ./thinclient_drives
--------------e---- ./flash_cc2531
--------------e---- ./Public
--------------e---- ./raspiBackup.msg
--------------e---- ./foo.txt
--------------e---- ./rpdiags.txt
--------------e---- ./log2ram.tar.gz
--------------e---- ./domoticz
--------------e---- ./udo systemctl status watchdog
--------------e---- ./Desktop
--------------e---- ./mu_code
--------------e---- ./Downloads
pi@Raspberrypi-2:~ $ ^C
pi@Raspberrypi-2:~ $ ^C
pi@Raspberrypi-2:~ $ stat thinclient_drives
  File: thinclient_drives
  Size: 0               Blocks: 0          IO Block: 4096   directory
Device: 2ah/42d Inode: 1           Links: 0
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 1970-01-01 01:00:00.000000000 +0100
Modify: 1970-01-01 01:00:00.000000000 +0100
Change: 1970-01-01 01:00:00.000000000 +0100
 Birth: -

**Comment by dolorosus** [comment] 2024-10-01 12:12
If no xrdp session is running, **I would** exclude the ```thinclient_drives``` directory from backup, since xrdp will create it if needed.
This is not a general recommendation, but this is what **i would do**.

And again: TEST your backup. Although the script was written before Raspbian on Debian 12 (bookworm), it has been adapted to Bookworm. It should also work with Raspbian Debian 11, but testing (and thus practicing the restore in case of disaster) is essential.

**Comment by framps** [comment] 2024-10-01 19:29
> I am not familiar with the `rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]` message.

It's a message used for any errors happening during transfer. A very common message is if you backup a running system that some files vanished during the xfer. This usually is no issue because temporary files are created and deleted during the backup. But you don't know for sure. Other messages handle access problems like in this case and that some attributes (xattrs) cannot be saved.

So it's best practice to get rid of these messages. Either you stop the services which create temporary files or you exclude the directories these temporary files are written into. 

Same for thinclient_drives: If they are not required to be included in the backup just exclude them.

JM2C :smile:

**Comment by dolorosus** [comment] 2024-10-01 19:47
When making a backup of a running system, it is advisable to run as few programs as possible.
The script [WeeklyBackup.sh](https://github.com/dolorosus/RaspiBackup/blob/master/WeeklyBackup.sh) could serve as an inspiration on how to proceed.


This thread now tends more towards general tips for backups and does not refer to errors in the backup script. Therefore I am closing this issue.

**Closed as completed by dolorosus** 2024-10-01 19:47 UTC

**Comment by framps** [comment] 2024-10-01 20:05
> This thread now tends more towards general tips for backups

I agree. I thought it would be helpful for you and the Raspberry community and users of your Raspberry backup tool to share experiences. I have no means other than this issue. 

There are a lot of other useful Raspberry backup tools out there I'm watching and I find your tool very useful. That's why I watch your repo and unfortunately by error thought this is issue is related to my backup tool :cry: I'm very sorry about this.

If you're interested to share Raspberry backup experiences let me know how I can get in contact with your.

One suggestion given this issue: Add an option to RaspiBackup to define directories to exclude from the backup

**Comment by dolorosus** [comment] 2024-10-01 20:17
This script is OSS you can do anything you want with it. Feel free to fork, change or improve it and create a pull request.
If you need more exclusions than the default exclusions, you can add them starting around line 290. 

If I ever have some time, I'll think about whether there is a generalized way to put the excludes into a file without breaking the script.

**Comment by framps** [comment] 2024-10-01 20:22
> Feel free to fork, change or improve it and create a pull request.

I think you misunderstand my previous comment. I have my own backup tool I like and use and I don't want to create any PR on your nice tool. It's just a suggestion to exchange experiences from my side.

If you don't want to - I'm fine

**Comment by JoostDkr** [comment] 2024-10-01 21:40
Thanks for your thoughts about my issue.
The error "_lsattr: Inappropriate ioctl for device While reading flags on ./thinclient_drives_" disappeared after the command "_fusermount -u ~/thinclient_drives_". It looks like the error shows when the RaspiBackup proces does not end  properly.
